sudo: false

matrix:
  fast_finish: true
  include:
    - python: "3.6"
      env: TOXENV=lint
      dist: xenial
    - python: "3.6"
      env: TOXENV=pylint
      dist: xenial
    - python: "3.6"
      env: TOXENV=typing
      dist: xenial
    - python: "3.6"
      env: TOXENV=py35
      dist: xenial
    - python: "3.6"
      env: TOXENV=py36
      dist: xenial
    - python: "3.7"
      env: TOXENV=py37
      dist: xenial
    - python: "3.8-dev"
      env: TOXENV=py38
      dist: xenial
  allow_failures:
    - python: "3.8-dev"
      env: TOXENV=py38
      dist: xenial

cache:
  directories:
    - $HOME/.cache/pip
install: pip install -U tox
language: python
script: travis_wait 30 tox
services:
  - docker
